import { 
  Camera, 
  Check, 
  ChevronDown, 
  ChevronLeft, 
  ChevronRight, 
  Command, 
  CreditCard, 
  File, 
  FileText, 
  Facebook,
  Instagram,
  Linkedin,
  HelpCircle, 
  Image, 
  Laptop, 
  Loader2, 
  LucideProps,
  Moon, 
  MoreVertical, 
  Plus, 
  Settings, 
  SunMedium, 
  Trash, 
  Twitter, 
  User, 
  X 
} from "lucide-react"

export type Icon = typeof Command

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: HelpCircle,
  user: User,
  camera: Camera,
  check: Check,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  // Social icons
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  twitter: Twitter,
} as const 